apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zigbee2mqtt
  labels:
    app: zigbee2mqtt
  {{- if .Values.tailscale.enabled }}
  annotations:
    tailscale.com/expose: "true"
    {{- if .Values.tailscale.hostname }}
    tailscale.com/hostname: {{ .Values.tailscale.hostname | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.tailscale.enabled }}
  type: LoadBalancer
  loadBalancerClass: tailscale
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: zigbee2mqtt
